export enum JobType {
  GENERATE_REPORT = 'GENERATE_REPORT',
  PROCESS_FILE = 'PROCESS_FILE',
  DELIVER_WEBHOOK = 'DELIVER_WEBHOOK',
  SEND_NOTIFICATION = 'SEND_NOTIFICATION',
  USER_ONBOARDING_WORKFLOW = 'USER_ONBOARDING_WORKFLOW',
}